### ISSUE TITLE
User can add a note

### ISSUE THREAD

**Issue by bernardinoa** [bernardinoa/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a note

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the "plus" icon off the "welcome note" (the user comes across when they first access the app) to create a new note - if the user deletes the welcome note, the only way to add a note would be with a drag-to-create-note action which is only doable in the next feature, [F2](https://github.com/bernardinoa/final-project/issues/2), also an alternative way to create a note

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="489" alt="Screen Shot 2021-11-03 at 3 42 09 PM" src="https://user-images.githubusercontent.com/88168364/140215325-cb5e1018-127e-4f8d-ba03-355b85d0bcd9.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

#### React

- [x] Create a "note" component which allows the user to create more individual "note" components by clicking the note component's "plus" icon

#### indexedDB

- [x] Create database/storage off [localForage](https://www.npmjs.com/package/localforage)
- [x] Use only the necessary schema from dbdesigner
- [x] Add `then` and `catch` on the `localForage` promise as necessary
- [x] Test by looking at browser console 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
