### ISSUE TITLE
User can drag a note

### ISSUE THREAD

**Issue by bernardinoa** [bernardinoa/final-project#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

After submitting a new note, the user will be able to drag a note anywhere within the window

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user's submitted note's toolbar will be draggable, i.e., the user will be able to click left on the mouse and hold the click when hovering over a note's toolbar to drag/move the note anywhere within the window

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="126" alt="Screen Shot 2021-11-10 at 1 21 53 PM" src="https://user-images.githubusercontent.com/88168364/141195435-f87feca3-4f3c-45b7-8659-7e4f38ab98bd.png">
<img width="188" alt="Screen Shot 2021-11-10 at 1 20 52 PM" src="https://user-images.githubusercontent.com/88168364/141195446-41d2363a-d6d3-4e55-943e-0c307c6f2ccc.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Install [Interact.js](https://interactjs.io/) via NPM
- [x] Update the `Note` component since it represents what we are interested in manipulating: an already "submitted" note
  - Import `interactjs` into the file
  - Call the `draggable` method within the `Note` component function outside the `return` expression - refer back to how rendering works in React
  - Call the [`draggable`](https://interactjs.io/docs/draggable/) method on the `note` class like so: `interact('.note').draggable({})`
  - Add options to the method call
- [x] Figure how to structure the window layout
  - What `display`/`position` property should `note` have? What `width` and `height` should a `note` have?

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
