### ISSUE TITLE
User can resize a note

### ISSUE THREAD

**Issue by bernardinoa** [bernardinoa/final-project#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can resize a note

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to hover over the bottom right of a given note to minimize (by dragging inwardly) or expand (by dragging outwardly) - hovering over the bottom presents an an arrow as a cursor to represent the possibility of minifying or expanding

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="313" alt="Screen Shot 2021-11-11 at 4 40 04 PM" src="https://user-images.githubusercontent.com/88168364/141389132-c42b2018-80ba-4c42-a2dd-03b911a18bf3.png">
<img width="301" alt="Screen Shot 2021-11-11 at 4 42 53 PM" src="https://user-images.githubusercontent.com/88168364/141389229-746a1f09-6119-4c80-918d-2a200a5937d5.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Update the `Note` component
  - Add a `resizable` method on the `Note` component
    - Add an edges property that represent which edge from the `Note` component can be changed (bottom right)
    - Add a `listeners` property with a `move` method
      - Refer to the `draggable` `move` method: do something similar
- [x] Make toolbar as the only draggable/grabbable aspect to move a `Note` component
  - Use `cursor: grab` and on active, `cursor: grabbing` (maybe see `interactjs` cursor styling defaults)
- [x] Add the ability to change from dark/light mode in the `Graph` component/view (add icon elements, etc)
- [x] Add favicons, app icons, etc

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
