### ISSUE TITLE
User can snap a new note

### ISSUE THREAD

**Issue by bernardinoa** [bernardinoa/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can "snap" a new note by dragging a window pane which will represent the size of the new note (a new note must be a certain width and height for it to be created)

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will see a grid-based layout and be able to "snap-to-grid" a new note anywhere within the confines of the window

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="310" alt="Screen Shot 2021-11-10 at 11 48 36 AM" src="https://user-images.githubusercontent.com/88168364/141183067-4ad79666-5938-40a8-96b9-7eb92d24f37b.png">
<img width="242" alt="Screen Shot 2021-11-10 at 11 49 09 AM" src="https://user-images.githubusercontent.com/88168364/141183087-3aa95356-972b-4496-b1f3-78bf1e46f5d7.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [ ] Install the [Interact.js](https://interactjs.io/) library
- [ ] Update the `AddNote` component
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
