### ISSUE TITLE
User can delete a note

### ISSUE THREAD

**Issue by bernardinoa** [bernardinoa/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a note

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will see a minus icon/character on the top right of a given, already-published note and the user will able to click it in order to delete the note - user can refresh their page to verify the note was deleted

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="461" alt="Screen Shot 2021-11-05 at 1 21 23 PM" src="https://user-images.githubusercontent.com/88168364/140573704-34f89651-13b9-4074-86fe-b3cd26c26c60.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Exchange the `add-icon` class for a `delete-icon` class on the "published" notes (AKA the `Note` component); exchange the add/plus character for a delete/minus character on the `Note` component (think about whether i should leave the icon/character as an anchor element or a button element)
- [x] Create a `handleDeleteClick` function (determine in what component it should be placed, or even if it should be a component itself)
- [x] Add a `onClick` prop on the `delete-icon` to add delete-a-note functionality
- [x] Update the state of `localforage` to account for a removed note
    - determine whether a `removeItem` method on `localforage` is necessary (and hence another `useEffect` hook), or the already-defined `useEffect` hook with `setItem`  on `localforage` accounts for the deleted note given the `handleDeleteClick` function (see `useEffect` on the React Docs)

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
