### ISSUE TITLE
User can add a note title

### ISSUE THREAD

**Issue by bernardinoa** [bernardinoa/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a title to their note

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user as an option of giving a note a title, if the user does not add a title to a note, the default title of the note is the note's id/index; the note title is placed in the center of the note's toolbar

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="735" alt="Screen Shot 2021-11-08 at 2 54 32 PM" src="https://user-images.githubusercontent.com/88168364/140831165-ffe373ba-c00d-4462-9a68-0697d4db63a4.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x]  Update the `Home` component  
  - Within the `addNote` function, specifically under the `newNote` object, add a `title` property with the value `title`
- [x] Update the `NotesList` component, specifically the return expression of the `Note` component, to include a `title` prop with a value of `note.title`
- [x] Update the `AddNote` component
  - determine whether declaring new state variables by array destructuring `setNoteTitle` and `titleText` is necessary
    - if so, do something similar to `noteText` with `noteTitle`, i.e., `handleSaveClick` sets the `title` back to an empty string, etc
  - Think about whether `title` should be a `textarea` or `span` element 
  - Pass `value` and `onChange` props to the `title` element
  - Much like the `noteText` condition, create a condition for `noteTitle` such that a user can't submit an empty `title` input
- [x] Update the `Note` component
  - pass the `title` as a parameter
  - add a `span` element to the return expression for `title`
  - create styling for `title` such that it is in the center of the toolbar
  - add a `className` prop with `title`'s class

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
