### ISSUE TITLE
User can swap views between notes and graph

### ISSUE THREAD

**Issue by bernardinoa** [bernardinoa/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can swap between two views: one where the notes are represented and one where the future graph visualization will be represented

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user may click on an icon (a note icon or a graph icon, depending on the view) in the bottom left of the app to switch views from notes representation to graph representation, and vice versa

The user will also be able to tell what view they are in by looking at the URL, i.e., `notes.app` (or `notes.app/#`- maybe unnecessary) for the notes view and `notes.app/#graph` for the graph view

The user will also be able to see a not found page, if they are in an invalid location, to indicate there is no content in that URL

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="499" alt="Screen Shot 2021-11-09 at 3 57 58 PM" src="https://user-images.githubusercontent.com/88168364/141024691-06a67a81-ac57-47a9-b0e3-0494cfbef838.png">
<img width="376" alt="Screen Shot 2021-11-09 at 4 45 36 PM" src="https://user-images.githubusercontent.com/88168364/141028927-fef83de4-8b8b-4c1e-9975-e8819b373989.png">
<img width="200" alt="Screen Shot 2021-11-09 at 4 50 21 PM" src="https://user-images.githubusercontent.com/88168364/141029365-288ceb80-f9d3-4d7b-a435-cb1eeb75f96f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Find and download a note and a graph icon (svg preferably)
- [x] Incorporate a `parseRoute` function (maybe in a new directory named `lib`)
- [x] Create a `404.jsx` file under the `pages` directory
  - Create a `NotFound` component and within it's return expression, add the notes and graph icons as `anchor` elements to indicate which view the user would like to go/return to
  - Style accordingly
- [x] Create a `graph.jsx` file under the `pages` directory
  - Create a new component called `Graph` and within it's `return` expression, have an `anchor` element which represents and points to the notes view 
- [x] Update the `App` component
  - Add a new state for a `route` property which itself has `path` and `params` properties - reference the `parseRoute` function in `lib`
  - Add a `componentDidMount` method and a `renderPage` method
    - In the `renderPage` method, we'll have two conditions:
      1. If `route.path` is an empty string, we return the `Home` component (AKA the notes)
      2. If `route.path` is `graph`, we return the `Graph` component
    - If the two above conditions are false, we return the `NotFound` component
  - Think about making the `App` component a hooks-based component instead of a class-based component

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
