### ISSUE TITLE
User can use app without a network connection

### ISSUE THREAD

**Issue by bernardinoa** [bernardinoa/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to use the app without a network connection

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the user's end, the app will function no differently whether the user has a network connection or not, i.e., the app will function normally, the user's data will be appended in storage as if the user had a network connection

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Install [`workbox-webpack-plugin`](https://www.npmjs.com/package/workbox-webpack-plugin)
- [x] Configure `webpack.config.js` accordingly
  - import `workbox-webpack-plugin`
  - create a new `workbox-webpack-plugin` instance
- [x] Adjust template `index.html` to include a service worker function script
  - service worker registration
- [x] Create a `manifest` file and include it in the `index.html` template
- [x] Test by ending express server

### 🧑‍⚕️ Clean Up

- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
